//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseSession
    {
        public int SessionID { get; set; }
        public int CaseID { get; set; }
        public Nullable<decimal> RollNumber { get; set; }
        public System.DateTime SessionDate { get; set; }
        public string SessionDetails { get; set; }
        public string SessionCommandsOrders { get; set; }
        public string SessionNotes { get; set; }
    
        public virtual Case Case { get; set; }
    }
}
