//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case()
        {
            this.CasePayments = new HashSet<CasePayment>();
            this.CaseSessions = new HashSet<CaseSession>();
            this.CLowers_Case = new HashSet<CLowers_Case>();
            this.Delegator_Case = new HashSet<Delegator_Case>();
        }
    
        public int CaseID { get; set; }
        public string AdminNumber { get; set; }
        public string AdminString { get; set; }
        public string FineNumber { get; set; }
        public string FineString { get; set; }
        public string InvestigationNumber { get; set; }
        public string InvestigationString { get; set; }
        public string ImprisonmentNumber { get; set; }
        public string ImprisonmentString { get; set; }
        public string PartialNumber { get; set; }
        public string PartialString { get; set; }
        public string TotalNumber { get; set; }
        public string TotalString { get; set; }
        public string DelegationNumber { get; set; }
        public string DelegationLetter { get; set; }
        public string DocumentationOffice { get; set; }
        public System.DateTime CaseRecevingDate { get; set; }
        public int OfficeID { get; set; }
        public int CourtID { get; set; }
        public int ChamberID { get; set; }
        public string CaseSubject { get; set; }
        public string CaseDetails { get; set; }
        public Nullable<decimal> TotalPresentAmount { get; set; }
        public Nullable<decimal> TotalInstallsAmount { get; set; }
        public Nullable<decimal> TotalRetensionAmount { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string ResponsibleLower { get; set; }
        public string DelegationString { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CasePayment> CasePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseSession> CaseSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLowers_Case> CLowers_Case { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delegator_Case> Delegator_Case { get; set; }
    }
}
