//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasePayment
    {
        public int PaymentDetailsId { get; set; }
        public int CaseID { get; set; }
        public int InstallmentType { get; set; }
        public decimal InstallmentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string InstallmentDetails { get; set; }
        public string PayerName { get; set; }
    
        public virtual Case Case { get; set; }
    }
}
