//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chamber
    {
        public int ChamberID { get; set; }
        public int CourtID { get; set; }
        public string ChamberName { get; set; }
        public string ChamberAdress { get; set; }
        public string ChamberDetails { get; set; }
        public string ChamberBossName { get; set; }
    
        public virtual Court Court { get; set; }
    }
}
