//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLowers_Case
    {
        public int CLowerID { get; set; }
        public int CaseID { get; set; }
        public string Notes { get; set; }
    
        public virtual CompetitorLower CompetitorLower { get; set; }
        public virtual Case Case { get; set; }
    }
}
