//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitorLower
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompetitorLower()
        {
            this.CLowers_Case = new HashSet<CLowers_Case>();
        }
    
        public int CLowerID { get; set; }
        public string CLowerName { get; set; }
        public string CLowerOffice { get; set; }
        public string CLowerDetails { get; set; }
        public string CLowerPhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLowers_Case> CLowers_Case { get; set; }
    }
}
