//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Court
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Court()
        {
            this.Chambers = new HashSet<Chamber>();
        }
    
        public int CourtID { get; set; }
        public string CourtName { get; set; }
        public int CourtRegionID { get; set; }
        public string CourtAddress { get; set; }
        public string CourtDetails { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chamber> Chambers { get; set; }
        public virtual Region Region { get; set; }
    }
}
