//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delegator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delegator()
        {
            this.Delegator_Case = new HashSet<Delegator_Case>();
        }
    
        public int DelID { get; set; }
        public string DelName { get; set; }
        public string DelAddress { get; set; }
        public string DelMobile { get; set; }
        public string DelPhone { get; set; }
        public string DelDetails { get; set; }
        public string DelSSN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delegator_Case> Delegator_Case { get; set; }
    }
}
