//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeArName { get; set; }
        public string EmployeeEnName { get; set; }
        public string EmployeeDetails { get; set; }
        public Nullable<int> EmployeeJobTitleID { get; set; }
        public Nullable<int> EmployeeDepID { get; set; }
    }
}
