//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int PhoneTypeID { get; set; }
        public int OfficeID { get; set; }
        public string PhoneType { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneDetails { get; set; }
    
        public virtual Office Office { get; set; }
    }
}
