//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowerApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartLowerEntities : DbContext
    {
        public SmartLowerEntities()
            : base("name=SmartLowerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CasePayment> CasePayments { get; set; }
        public virtual DbSet<CaseSession> CaseSessions { get; set; }
        public virtual DbSet<Chamber> Chambers { get; set; }
        public virtual DbSet<CLowers_Case> CLowers_Case { get; set; }
        public virtual DbSet<CompetitorLower> CompetitorLowers { get; set; }
        public virtual DbSet<Court> Courts { get; set; }
        public virtual DbSet<Delegator> Delegators { get; set; }
        public virtual DbSet<Delegator_Case> Delegator_Case { get; set; }
        public virtual DbSet<DocumentationOffice> DocumentationOffices { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
    }
}
